SELECT
  value
FROM
  V$NLS_PARAMETERS
WHERE
  parameter = 'NLS_DATE_FORMAT';
  
 SELECT sysdate FROM dual;
 
-- change the date format of session
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

SELECT sysdate FROM dual;

SELECT
  TO_CHAR( SYSDATE, 'FMMonth DD, YYYY' )
FROM
  dual;
  
 
 SELECT
  value
FROM
  V$NLS_PARAMETERS
WHERE
  parameter = 'NLS_DATE_LANGUAGE';
  
 ALTER SESSION SET NLS_DATE_LANGUAGE = 'FRENCH';
 

-- FRENCH Lnagual month
SELECT
  TO_CHAR( SYSDATE, 'FMMonth DD, YYYY' )
FROM
  dual;
  
 
 ALTER SESSION SET NLS_DATE_LANGUAGE = 'AMERICAN';


--Convert string to date

SELECT to_date('August 01, 2018', 'Month, dd, yyyy') FROM dual;

SELECT
  DECODE( TIMESTAMP '1999-01-15 8:00:00 -8:00', 
          TIMESTAMP '1999-01-15 11:00:00 -5:00', 
          'Equal', 
          'Not Equal' )
FROM
  dual;
 
 CREATE TABLE logs
  (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    log_message VARCHAR2(255) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,  
    PRIMARY KEY(log_id)
  );
 
 SELECT SESSIONTIMEZONE FROM dual;

INSERT INTO logs(log_message, created_at)
VALUES('Insert a timestamp',TIMESTAMP '2017-08-08 2:00:00');

SELECT * FROM logs;

select name as "Service Name" from V$active_services;
